image: Visual Studio 2022
version: 2.0.{build}
configuration: Release

init:
- if "%APPVEYOR_REPO_NAME%" == "JeremyAnsel/OPTech" if "%APPVEYOR_REPO_BRANCH%"=="master" if not defined APPVEYOR_PULL_REQUEST_NUMBER set DEPLOY=True

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'

before_build:
- nuget restore OPTech\OPTech.sln

build:
  project: OPTech\OPTech.sln
  verbosity: minimal

after_build:
- OPTech\build-dist.cmd

artifacts:
- path: OPTech\dist
  name: OPTech-$(APPVEYOR_BUILD_VERSION)
  type: zip
